version: '3'
services:
  db:
    image: mysql:8.0.36
    container_name: mysql2
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - .dbdata:/var/lib/mysql
      
  web:
    image: flask:3.0.2
    container_name: flask
    build: .
    command: 'python main.py'
    volumes:
      - .:/boss
    ports:
      - 8001:5000
    depends_on:
      - db