# Generated by Django 5.0.3 on 2024-03-09 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=20)),
                ("shop_address", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data ordered"
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("deliver_finish", models.BooleanField(default=0)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_order.shop",
                    ),
                ),
            ],
        ),
    ]
